In [40]:
# 질병관리 본부 그래프 따라 그리기 
import pandas as pd

data =pd.read_csv('./data/daily_Confirmed.csv', index_col = ['Date'])
data

,Female,Male,0-9,10-,20-29,30-39,40-49,50-59,60-69,70-79,80-,Sum,daily_count
Date,,,,,,,,,,,,,
2020-02-18,15,16,0.0,0.0,6.0,6.0,6.0,8.0,3.0,1.0,1.0,31,NaN
2020-02-19,26,20,0.0,1.0,10.0,7.0,9.0,11.0,5.0,2.0,1.0,46,15.0
2020-02-20,62,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104,58.0
2020-02-21,122,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,204,100.0
2020-02-22,180,166,0.0,5.0,53.0,41.0,56.0,94.0,75.0,18.0,4.0,346,142.0
2020-02-23,314,242,1.0,7.0,107.0,62.0,93.0,141.0,109.0,30.0,6.0,556,210.0
2020-02-24,460,303,2.0,10.0,153.0,94.0,127.0,192.0,135.0,41.0,9.0,763,207.0
2020-02-25,550,343,4.0,22.0,196.0,113.0,146.0,222.0,142.0,39.0,9.0,893,130.0
2020-02-26,709,437,3.0,31.0,276.0,144.0,175.0,267.0,184.0,51.0,15.0,1146,253.0
2020-02-27,980,615,9.0,50.0,444.0,193.0,234.0,347.0,226.0,72.0,20.0,1595,449.0
2020-02-28,1252,770,13.0,74.0,558.0,252.0,300.0,434.0,270.0,91.0,30.0,2022,427.0
2020-02-29,1837,1094,19.0,96.0,856.0,361.0,437.0,587.0,390.0,131.0,54.0,2931,909.0
2020-03-01,2197,1329,27.0,137.0,1054.0,426.0,521.0,687.0,453.0,158.0,63.0,3526,595.0
2020-03-02,2621,1591,32.0,169.0,1235.0,506.0,633.0,834.0,530.0,192.0,81.0,4212,686.0
2020-03-03,3002,1810,34.0,204.0,1417.0,578.0,713.0,952.0,597.0,224.0,93.0,4812,600.0
2020-03-04,3332,1996,34.0,233.0,1575.0,631.0,790.0,1051.0,646.0,260.0,108.0,5328,516.0
2020-03-05,3617,2149,38.0,257.0,1727.0,659.0,847.0,1127.0,699.0,288.0,124.0,5766,438.0
2020-03-06,3939,2345,45.0,292.0,1877.0,693.0,889.0,1217.0,763.0,340.0,168.0,6284,518.0
2020-03-07,4245,2522,52.0,327.0,2028.0,727.0,941.0,1287.0,830.0,384.0,191.0,6767,483.0
2020-03-08,4440,2694,58.0,360.0,2133.0,760.0,975.0,1349.0,878.0,409.0,212.0,7134,367.0
2020-03-09,4583,2799,66.0,381.0,2190.0,779.0,1005.0,1391.0,916.0,438.0,216.0,7382,248.0
2020-03-10,4661,2852,67.0,393.0,2213.0,789.0,1030.0,1416.0,929.0,454.0,222.0,7513,131.0
2020-03-11,4808,2947,75.0,405.0,2238.0,804.0,1082.0,1472.0,960.0,483.0,236.0,7755,242.0
2020-03-12,4875,2994,76.0,412.0,2261.0,812.0,1101.0,1495.0,972.0,497.0,243.0,7869,114.0
2020-03-13,4936,3043,77.0,421.0,2274.0,823.0,1117.0,1523.0,985.0,506.0,253.0,7979,110.0
2020-03-14,4986,3100,81.0,424.0,2287.0,833.0,1133.0,1551.0,999.0,515.0,263.0,8086,107.0
2020-03-15,5026,3136,83.0,427.0,2301.0,842.0,1141.0,1568.0,1012.0,525.0,263.0,8162,76.0
2020-03-16,5067,3169,85.0,432.0,2313.0,849.0,1147.0,1585.0,1024.0,531.0,270.0,8236,74.0
2020-03-17,5120,3200,86.0,436.0,2330.0,856.0,1164.0,1602.0,1033.0,539.0,274.0,8320,84.0
2020-03-18,5173,3240,87.0,438.0,2342.0,873.0,1171.0,1615.0,1059.0,542.0,286.0,8413,93.0
2020-03-19,5269,3296,91.0,444.0,2358.0,886.0,1181.0,1642.0,1080.0,562.0,321.0,8565,152.0
2020-03-20,5322,3330,97.0,452.0,2365.0,893.0,1193.0,1656.0,1099.0,568.0,329.0,8652,87.0
2020-03-21,5412,3387,99.0,457.0,2380.0,900.0,1203.0,1672.0,1118.0,589.0,381.0,8799,147.0
2020-03-22,5467,3430,101.0,460.0,2396.0,909.0,1221.0,1691.0,1132.0,595.0,392.0,8897,98.0

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 2020-02-18 to 2020-03-22
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Female       34 non-null     int64
 1   Male         34 non-null     int64
 2   0-9          32 non-null     float64
 3   10-          32 non-null     float64
 4   20-29        32 non-null     float64
 5   30-39        32 non-null     float64
 6   40-49        32 non-null     float64
 7   50-59        32 non-null     float64
 8   60-69        32 non-null     float64
 9   70-79        32 non-null     float64
 10  80-          32 non-null     float64
 11  Sum          34 non-null     int64
 12  daily_count  33 non-null     float64
dtypes: float64(10), int64(3)
memory usage: 3.7+ KB

In [42]:
# 3월 1일 부터 분석 시작
data = data.loc['2020-03-01': , ]
data

,Female,Male,0-9,10-,20-29,30-39,40-49,50-59,60-69,70-79,80-,Sum,daily_count
Date,,,,,,,,,,,,,
2020-03-01,2197,1329,27.0,137.0,1054.0,426.0,521.0,687.0,453.0,158.0,63.0,3526,595.0
2020-03-02,2621,1591,32.0,169.0,1235.0,506.0,633.0,834.0,530.0,192.0,81.0,4212,686.0
2020-03-03,3002,1810,34.0,204.0,1417.0,578.0,713.0,952.0,597.0,224.0,93.0,4812,600.0
2020-03-04,3332,1996,34.0,233.0,1575.0,631.0,790.0,1051.0,646.0,260.0,108.0,5328,516.0
2020-03-05,3617,2149,38.0,257.0,1727.0,659.0,847.0,1127.0,699.0,288.0,124.0,5766,438.0
2020-03-06,3939,2345,45.0,292.0,1877.0,693.0,889.0,1217.0,763.0,340.0,168.0,6284,518.0
2020-03-07,4245,2522,52.0,327.0,2028.0,727.0,941.0,1287.0,830.0,384.0,191.0,6767,483.0
2020-03-08,4440,2694,58.0,360.0,2133.0,760.0,975.0,1349.0,878.0,409.0,212.0,7134,367.0
2020-03-09,4583,2799,66.0,381.0,2190.0,779.0,1005.0,1391.0,916.0,438.0,216.0,7382,248.0
2020-03-10,4661,2852,67.0,393.0,2213.0,789.0,1030.0,1416.0,929.0,454.0,222.0,7513,131.0
2020-03-11,4808,2947,75.0,405.0,2238.0,804.0,1082.0,1472.0,960.0,483.0,236.0,7755,242.0
2020-03-12,4875,2994,76.0,412.0,2261.0,812.0,1101.0,1495.0,972.0,497.0,243.0,7869,114.0
2020-03-13,4936,3043,77.0,421.0,2274.0,823.0,1117.0,1523.0,985.0,506.0,253.0,7979,110.0
2020-03-14,4986,3100,81.0,424.0,2287.0,833.0,1133.0,1551.0,999.0,515.0,263.0,8086,107.0
2020-03-15,5026,3136,83.0,427.0,2301.0,842.0,1141.0,1568.0,1012.0,525.0,263.0,8162,76.0
2020-03-16,5067,3169,85.0,432.0,2313.0,849.0,1147.0,1585.0,1024.0,531.0,270.0,8236,74.0
2020-03-17,5120,3200,86.0,436.0,2330.0,856.0,1164.0,1602.0,1033.0,539.0,274.0,8320,84.0
2020-03-18,5173,3240,87.0,438.0,2342.0,873.0,1171.0,1615.0,1059.0,542.0,286.0,8413,93.0
2020-03-19,5269,3296,91.0,444.0,2358.0,886.0,1181.0,1642.0,1080.0,562.0,321.0,8565,152.0
2020-03-20,5322,3330,97.0,452.0,2365.0,893.0,1193.0,1656.0,1099.0,568.0,329.0,8652,87.0
2020-03-21,5412,3387,99.0,457.0,2380.0,900.0,1203.0,1672.0,1118.0,589.0,381.0,8799,147.0
2020-03-22,5467,3430,101.0,460.0,2396.0,909.0,1221.0,1691.0,1132.0,595.0,392.0,8897,98.0

In [43]:
# 데이터 형변환 float -> int 형으로 
data= data.astype(int)
data.dtypes

Female         int32
Male           int32
0-9            int32
10-            int32
20-29          int32
30-39          int32
40-49          int32
50-59          int32
60-69          int32
70-79          int32
80-            int32
Sum            int32
daily_count    int32
dtype: object

In [44]:
# 10 - : rename -> 10 - 19 
data.rename(columns = {data.columns[3]: '10-19'})

,Female,Male,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80-,Sum,daily_count
Date,,,,,,,,,,,,,
2020-03-01,2197,1329,27,137,1054,426,521,687,453,158,63,3526,595
2020-03-02,2621,1591,32,169,1235,506,633,834,530,192,81,4212,686
2020-03-03,3002,1810,34,204,1417,578,713,952,597,224,93,4812,600
2020-03-04,3332,1996,34,233,1575,631,790,1051,646,260,108,5328,516
2020-03-05,3617,2149,38,257,1727,659,847,1127,699,288,124,5766,438
2020-03-06,3939,2345,45,292,1877,693,889,1217,763,340,168,6284,518
2020-03-07,4245,2522,52,327,2028,727,941,1287,830,384,191,6767,483
2020-03-08,4440,2694,58,360,2133,760,975,1349,878,409,212,7134,367
2020-03-09,4583,2799,66,381,2190,779,1005,1391,916,438,216,7382,248
2020-03-10,4661,2852,67,393,2213,789,1030,1416,929,454,222,7513,131
2020-03-11,4808,2947,75,405,2238,804,1082,1472,960,483,236,7755,242
2020-03-12,4875,2994,76,412,2261,812,1101,1495,972,497,243,7869,114
2020-03-13,4936,3043,77,421,2274,823,1117,1523,985,506,253,7979,110
2020-03-14,4986,3100,81,424,2287,833,1133,1551,999,515,263,8086,107
2020-03-15,5026,3136,83,427,2301,842,1141,1568,1012,525,263,8162,76
2020-03-16,5067,3169,85,432,2313,849,1147,1585,1024,531,270,8236,74
2020-03-17,5120,3200,86,436,2330,856,1164,1602,1033,539,274,8320,84
2020-03-18,5173,3240,87,438,2342,873,1171,1615,1059,542,286,8413,93
2020-03-19,5269,3296,91,444,2358,886,1181,1642,1080,562,321,8565,152
2020-03-20,5322,3330,97,452,2365,893,1193,1656,1099,568,329,8652,87
2020-03-21,5412,3387,99,457,2380,900,1203,1672,1118,589,381,8799,147
2020-03-22,5467,3430,101,460,2396,909,1221,1691,1132,595,392,8897,98

In [45]:
data2 = pd.read_csv('./data/total.csv' ,index_col = ['date'])
data2

                총계   확진자  격리해제   격리중   사망    검사중   결과 음성
date
2020-03-01   96985  3526    30  3479   17  32422   61037
2020-03-02  109591  4212    31  4159   22  33799   71580
2020-03-03  125851  4812    34  4750   28  35555   85484
2020-03-04  136707  5328    41  5255   32  28414  102965
2020-03-05  146541  5766    88  5643   35  21810  118965
2020-03-06  164740  6284   108  6134   42  21832  136624
2020-03-07  178189  6767   118  6605   44  19620  151802
2020-03-08  188518  7134   130  6954   50  19376  162008
2020-03-09  196618  7382   166  7165   51  17458  171778
2020-03-10  210144  7513   247  7212   54  18452  184179
2020-03-11  222395  7755   288  7407   60  18540  196100
2020-03-12  234998  7869   333  7470   66  17727  209402
2020-03-13  248647  7979   410  7402   67  17940  222728
2020-03-14  261335  8086   714  7300   72  17634  235615
2020-03-15  268212  8162   834  7253   75  16272  243778
2020-03-16  274504  8236  1137  7024   75  14971  251297
2020-03-17  286716  8321  1401  6838   81  17291  261105
2020-03-18  295647  8413  1540  6789   84  16346  270888
2020-03-19  307024  8565  1947  6527   91  15904  282555
2020-03-20  316664  8652  2233  6325   94  15525  292487
2020-03-21  327509  8799  2612  6085  102  15704  303006
2020-03-22  331780  8897  2909  5884  104  14540  308343
2020-03-23  338036  8961  3166  5684  111  13628  315447
2020-03-24  348582  9037  3507  5410  120  15440  324105
2020-03-25  357896  9137  3730  5281  126  14278  334481
2020-03-26  364942  9241  4144  4966  131  14369  341332
2020-03-27  376961  9332  4528  4665  139  15219  352410
2020-03-28  387925  9478  4811  4523  144  16564  361883
2020-03-29  394141  9583  5033  4398  152  15028  369530
2020-03-30  395194  9661  5228  4275  158  13531  372002
2020-03-31  410564  9786  5408  4216  162  16892  383886
2020-04-01  421547  9887  5567  4155  165  16585  395075

In [47]:
# 일일확진자수, 일일격리해제수, 일일사망자수 구하기

Daily_confirmed=[]
Daily_recoverd=[]
Daily_death=[]
Daily_confirmed.append(595) # 3월 1일 일일확진자수는 질병관리본부에서 가져옴
Daily_recoverd.append(3)  # 3월 1일 일일격리해제수는 질병관리본부에서 가져옴
Daily_death.append(1) # 3월 1일 일일사망자수는 질병관리본부에서 가져옴

for i in range(len(data2)-1) :
    Daily_confirmed.append(data2.iloc[:,1][i+1] - data2.iloc[:,1][i])
    Daily_recoverd.append(data2.iloc[:,2][i+1] - data2.iloc[:,2][i])
    Daily_death.append(data2.iloc[:,4][i+1] - data2.iloc[:,4][i])

a = pd.DataFrame(Daily_confirmed, index = data2.index)
a = a.rename(columns = {0:"일일확진자"})

b = pd.DataFrame(Daily_recoverd, index = data2.index)
b = b.rename(columns = {0:"일일격리해제"})

c = pd.DataFrame(Daily_death, index = data2.index)
c = c.rename(columns = {0:"일일사망"})

today = pd.concat([data2, a, b, c], axis =1)
today

                총계   확진자  격리해제   격리중   사망    검사중   결과 음성  일일확진자  일일격리해제  일일사망
date
2020-03-01   96985  3526    30  3479   17  32422   61037    595       3     1
2020-03-02  109591  4212    31  4159   22  33799   71580    686       1     5
2020-03-03  125851  4812    34  4750   28  35555   85484    600       3     6
2020-03-04  136707  5328    41  5255   32  28414  102965    516       7     4
2020-03-05  146541  5766    88  5643   35  21810  118965    438      47     3
2020-03-06  164740  6284   108  6134   42  21832  136624    518      20     7
2020-03-07  178189  6767   118  6605   44  19620  151802    483      10     2
2020-03-08  188518  7134   130  6954   50  19376  162008    367      12     6
2020-03-09  196618  7382   166  7165   51  17458  171778    248      36     1
2020-03-10  210144  7513   247  7212   54  18452  184179    131      81     3
2020-03-11  222395  7755   288  7407   60  18540  196100    242      41     6
2020-03-12  234998  7869   333  7470   66  17727  209402    114      45     6
2020-03-13  248647  7979   410  7402   67  17940  222728    110      77     1
2020-03-14  261335  8086   714  7300   72  17634  235615    107     304     5
2020-03-15  268212  8162   834  7253   75  16272  243778     76     120     3
2020-03-16  274504  8236  1137  7024   75  14971  251297     74     303     0
2020-03-17  286716  8321  1401  6838   81  17291  261105     85     264     6
2020-03-18  295647  8413  1540  6789   84  16346  270888     92     139     3
2020-03-19  307024  8565  1947  6527   91  15904  282555    152     407     7
2020-03-20  316664  8652  2233  6325   94  15525  292487     87     286     3
2020-03-21  327509  8799  2612  6085  102  15704  303006    147     379     8
2020-03-22  331780  8897  2909  5884  104  14540  308343     98     297     2
2020-03-23  338036  8961  3166  5684  111  13628  315447     64     257     7
2020-03-24  348582  9037  3507  5410  120  15440  324105     76     341     9
2020-03-25  357896  9137  3730  5281  126  14278  334481    100     223     6
2020-03-26  364942  9241  4144  4966  131  14369  341332    104     414     5
2020-03-27  376961  9332  4528  4665  139  15219  352410     91     384     8
2020-03-28  387925  9478  4811  4523  144  16564  361883    146     283     5
2020-03-29  394141  9583  5033  4398  152  15028  369530    105     222     8
2020-03-30  395194  9661  5228  4275  158  13531  372002     78     195     6
2020-03-31  410564  9786  5408  4216  162  16892  383886    125     180     4
2020-04-01  421547  9887  5567  4155  165  16585  395075    101     159     3